version: '2.2'
services:
  quantacore:
    image: quantalabs/quanta-core:latest
    environment:
      - cluster.name=docker-cluster
      - BITSHARESD_PLUGINS=witness market_history
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/var/lib/bitshares
      - ./config:/etc/bitshares